package tachyon:accelerator@4.0.0;

interface npu {
    record invocation-error {
        message: string,
        upstream-status: option<u16>,
        invalid-request: bool,
    }

    record invocation-result {
        payload: list<u8>,
        metadata: list<tuple<string, string>>,
    }

    load-component: func(alias: string) -> result<u32, string>;
    invoke: func(component-id: u32, payload: list<u8>) -> result<invocation-result, invocation-error>;
}
